# Generated by Django 4.0.6 on 2022-07-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_user'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_students',
            field=models.ManyToManyField(blank=True, to='students.student'),
        ),
    ]
